# Generated by Django 5.1.6 on 2025-02-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_feedback_color_feedback_sleeve_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buy',
            name='sleeve_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
