# Generated by Django 5.1.6 on 2025-02-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_buy_color_buy_sleeve_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='color',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='sleeve_type',
        ),
    ]
