# Generated by Django 5.1.6 on 2025-02-13 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_feedback_color_remove_feedback_sleeve_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delpro',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='delpro',
            name='delivery',
        ),
        migrations.DeleteModel(
            name='Payment_status',
        ),
        migrations.DeleteModel(
            name='Product_quantity',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
        migrations.DeleteModel(
            name='delpro',
        ),
    ]
