# Generated by Django 5.1.6 on 2025-02-13 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_delpro_buy_remove_delpro_delivery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.register'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_id',
            field=models.CharField(max_length=36),
        ),
        migrations.AlterField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='signature_id',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=254),
        ),
    ]
